Simplemooc/courses/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from . import views

urlpatterns = [
    path('', views.index, name = 'index'),
   #path('<int:pk>', views.details, name = 'details') #regular expression para receber uma url com base na pk de um curso
    path('<slug:slug>', views.details, name = 'details'),
    path('<slug:slug>/inscricao', views.enrollments, name='enrollment'),
    path('<slug:slug>/anuncios', views.announcements, name='announcements'),
    path('<slug:slug>/cancelar-inscricao', views.undo_enrollment, name = 'undo-enrollment'),
    path('<slug:slug>/anuncios/<int:pk>', views.show_announcement, name = 'show-announcement'),
    path('<slug:slug>/aulas', views.lessons, name = 'lessons'),
    path('<slug:slug>/aulas/<int:pk>', views.lesson, name = 'lesson'),
    path('<slug:slug>/aulas/materiais/<int:pk>', views.material, name = 'material')
]

Simplemooc/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from .core import urls as core_urls
from .courses import urls as course_urls
from .accounts import urls as accounts_urls
from .forum import urls as forum_urls

urlpatterns = [
    path('admin/', admin.site.urls),

    path(r'', include((core_urls, 'core'), namespace = 'core')),
    path(r'cursos/', include((course_urls, 'courses'), namespace = 'courses')),
    path(r'conta/', include((accounts_urls, 'accounts'), namespace = 'accounts')),
    path(r'forum/', include((forum_urls, 'forum'), namespace = 'forum'))
]

Simplemooc/courses/models.py
from django import conf
from django.conf import settings
from django.db import models
from django.utils import timezone

from Simplemooc.core.mail import send_mail_template

class CourseManager(models.Manager):
    def search(self, query):
        #retorna o curso onde o nome ou a descrição contem a entrada de pesquisa
        return self.get_queryset().filter(
            models.Q(name__icontains=query),
            models.Q(description__icontains=query)
        )

class Course(models.Model):
    name = models.CharField("Nome", max_length=100)
    slug = models.SlugField('Atalho')
    description = models.TextField('Descrição simples', blank=True)
    about = models.TextField('Sobre o curso', blank=True)

    start_date = models.DateField('Data de início', blank=True, null=True)

    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    updated_at = models.DateField('Editado em', auto_now=True)

    image = models.ImageField(upload_to = 'courses/images', verbose_name='Imagem', blank=True, null=True)

    objects = CourseManager() #define o método de pesquisa da tabela

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return (self.slug) #retorna o endereço dos cursos dos slugs correspondentes
    
    def release_lessons(self):
        today = timezone.now().date()
        return (self.course_lesson.filter(release_date__gte=today))

    class Meta:
        verbose_name = 'Curso'
        verbose_name_plural = 'Cursos'

        ordering = ['name']

class Enrollments(models.Model):
    STATUS_CHOICES = (
        (0, 'Pendente'),
        (1, 'Aprovado'),
        (2, 'Cancelado'),
        (3, 'Indisponível')
    )

    #Esses dois atributos referenciam as duas classes pai, cursos e usuários
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, 
    related_name = 'enrollments_user', verbose_name='Usuário')
    course = models.ForeignKey(Course, on_delete=models.RESTRICT, 
    related_name='enrollments_course', verbose_name='Curso')

    #Inteiro representando opções
    status = models.IntegerField('Situação', choices=STATUS_CHOICES, default=0, blank=True)

    created_at = models.DateTimeField('Criado em', auto_now_add=True, blank=True)

    updated_at = models.DateTimeField('Atualizado em', auto_now=True, blank=True)

    def activate(self):
        self.status = 1
        self.save()
    
    def is_approved(self):
        if self.status == 1:
            return True
        return False

    class Meta:
        verbose_name = 'Inscrição'
        verbose_name_plural = 'Inscrições'
        ordering = ['course']
        unique_together = (('user', 'course'),)
        #Essa instrução define que não podera haver o mesmo usuário inscrito no mesmo curso duas vezes
    
class Announcements(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name='Curso', 
    related_name='course_announcements')
    title = models.CharField('Título', max_length=100)
    content = models.TextField('Conteúdo')

    created_at = models.DateTimeField('Criado em', auto_now_add=True, blank=True)
    updated_at = models.DateTimeField('Atualizado em', auto_now=True, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Anúncio'
        verbose_name_plural = 'Anúncios'
        ordering = ['course','-created_at']

class Comments(models.Model):
    announcement = models.ForeignKey(Announcements, on_delete=models.CASCADE, verbose_name='Anúncio',
    related_name='announcements_comments')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Usuário')
    comment = models.TextField('Comentário')

    created_at = models.DateTimeField('Criado em', auto_now_add = True, blank = True)
    updated_at = models.DateTimeField('Atualizado em', auto_now = True, blank = True)

    def __str__(self):
        #return (self.comment[:20] + '...')
        return (self.user.username[:] + ', '+ self.announcement.course.name[:] +', '+ self.announcement.title[:] +', ' + str(self.created_at))

    class Meta:
        verbose_name = 'Comentário'
        verbose_name_plural = 'Comentários'
        ordering = ['announcement','created_at']
    
class Lesson(models.Model):

    name = models.CharField('Nome', max_length=100)
    description = models.TextField('Descrição', blank = True)
    number = models.IntegerField('Número (ordem)', blank = True, default=0)
    release_date = models.DateTimeField('Data de lançamento', blank = True, null = True)

    created_at = models.DateTimeField('Criado em', auto_now_add=True, blank=True)
    updated_at = models.DateTimeField('Atualizado em', auto_now=True, blank = True)

    course = models.ForeignKey(Course, on_delete = models.CASCADE, related_name='course_lesson')

    def __str__(self):
        return self.name

    def is_avaible(self):
        if self.release_date:
            today = timezone.now().date()
            return self.release_date <= today
        return False    
    # Recebe a informação de que a aula foi lançado ou não, comparando a data de lançamento à atual

    class Meta:
        verbose_name = 'Aula'
        verbose_name_plural = 'Aulas'
        ordering = ['number']

class Material(models.Model):
    title = models.CharField('Título', max_length=100)
    embedded = models.TextField('Vídeo embedded', blank = True)
    file = models.FileField(upload_to='lessons/materials', blank = True, null=True)

    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE, related_name='lesson_material')

    def is_embedded(self):
        return(self.embedded)

    def __str__(self):
        return(self.title)

    class Meta:
        verbose_name = 'Material'
        verbose_name_plural = 'Materiais'

def post_save_announcements(instance, created, **kwargs):
    if created: # Verifica se o anúncio foi criado
        subject = instance.title # Recebe o título do anúncio
        context = {
            'announcement' : instance # Salva o anúncio no contexto
        }

        template_name = 'mail/send_announcement.html'
        enrollments = Enrollments.objects.filter(course = instance.course, status=1)
        # Lista com todas as inscrições válidas referentes ao curso

        for enrollment in enrollments: # Varre a lista de alunos no curso
            recipient_list = [enrollment.user.email] # Salva o email do aluno inscrito no curso
            send_mail_template(subject=subject, template_name=template_name, context=context,
            recipient_list=recipient_list) # Envia o email ao aluno
    
models.signals.post_save.connect(post_save_announcements, sender = Announcements,
 dispatch_uid='post_save_announcements')

Simplemooc/courses/forms.py
from django import forms
from django.core.mail import send_mail
from django.conf import settings

from Simplemooc.core.mail import send_mail_template
from Simplemooc.courses.models import Comments

class ContactCourse(forms.Form):
    name = forms.CharField(label='Nome', max_length=100)
    email = forms.EmailField(label='Email')

    message = forms.CharField(label='Mensagem/Dúvida', widget=forms.Textarea)
    #O widget define a forma da entrada, já que não há um form.TextField

    #É possível usar o argumento required = False para atributos opcionais 

    def send_mail(self, course):
        subject = '[%s] Curso', course
        message = 'Nome: %(name)s;Email: %(email)s;Mensagem: %(message)s'
        context = {
            'name' : self.cleaned_data['name'],
            'email': self.cleaned_data['email'],
            'message': self.cleaned_data['message']
        } #Atribui os dados do email

        template_name = 'courses\mail.html'

        send_mail_template(subject, template_name, context, [settings.CONTACT_EMAIL]) 
        #settings.CONTACT_EMAIL deve estar entre colchetes, a lista de recipientes é, bom, uma lista

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comments
        fields = ['comment']
    

Simplemooc/courses/views.py
from django import contrib
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.mail import message
from django.shortcuts import get_object_or_404, redirect, render
from django.template.loader import render_to_string

from .models import Announcements, Course, Enrollments, Lesson, Material #Referencia a tabela Course do BD
from .forms import CommentForm, ContactCourse #Chamado ao form de contato do app
from .decorators import enrollment_required

# Create your views here.

def index(request):
    courses = Course.objects.all() #Possui todos os objetos da tabela Course 
    template_name = 'courses/index.html'

    context = {
        'courses' : courses #Adiciona course ao contexto do template
    }
    return render(request, template_name, context)

'''
def details(request, pk):
    #course = Course.objects.get(pk = pk) #Filtra o curso com o atributo passado (pk), retorna uma exceção desagradável se não houver correspondência
    course = get_object_or_404(Course, pk = pk) #Retorna um 404 se não houver correspondência
    template_name = 'courses/details.html'

    context = {
        'course' : course
    }

    return render(request, template_name, context)'''

def details(request, slug):
    course = get_object_or_404(Course, slug = slug)
    context = {}

    if request.method == 'POST':
        form = ContactCourse(request.POST)
        if form.is_valid(): #Verifica se o formulário foi dvidamente preenchido
            context['is_valid'] = True #Auxiliar para o template

            '''for field in form:
                print(field.label, field.data) #Retorna os valores no terminal'''

            form.send_mail(course)#Método para enviar um email para o terminal
            form = ContactCourse()
    else:
        form = ContactCourse()

    template_name = 'courses/details.html'

    context['forms'] = form
    context['course'] = course

    return render(request, template_name, context)

@login_required
def enrollments(request, slug):
    course = get_object_or_404(Course, slug = slug) # Verifica se o curso está presente no BD
    enrollment, create = Enrollments.objects.get_or_create(
        user = request.user, course=course
        )
    # A primeira variável cria sempre, a segunda somente se a inscrição foi criado agora
    
    if create:
        enrollment.activate()
        messages.success(request, 'Inscrição realizada com sucesso!')
    # Ativa a inscrição, e informa ao usuário se ela não foi previamente criada
    
    else:
        messages.info(request, 'Você já está inscrito nesse curso')

    return redirect('accounts:dashboard')

@login_required
@enrollment_required
def announcements(request, slug):
    '''
    course = get_object_or_404(Course, slug = slug)

    if not request.user.is_staff: # Verifica se o membro é da equipe antes de tudo
        enrollment = get_object_or_404(Enrollments, user = request.user, course = course)
        if not enrollment.is_approved():
            messages.error(request, 'A sua inscrição está pendente')
            return redirect('accounts:dashboard')
    '''
    course = request.course # Passa o curso presente no contexto, que no caso, vem pelo decorator @enrollment_required
    template_name = 'courses/announcements.html'
    context = {
        'course' : course,
        'announcements' : course.course_announcements.all()
    }
    
    return render(request, template_name, context)

@login_required
@enrollment_required
def show_announcement(request, slug, pk):
    course = request.course

    announcement = get_object_or_404(course.course_announcements.all(), pk = pk)
    #Pega um anúncio específico de um curso específico, usa o related_name 
    
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.user = request.user
        comment.announcement = announcement
        comment.save()
        form = CommentForm()
        messages.success(request, 'O seu comentário foi enviado com sucesso')

    template_name = 'courses/show_announcement.html'
    context = {
        'course' : course,
        'announcement' : announcement,
        'form' : form,
    }

    return render(request, template_name, context)

@login_required
def undo_enrollment(request, slug):
    course = get_object_or_404(Course, slug = slug)
    enrollment = get_object_or_404(Enrollments, course = course, user = request.user)

    if request.method == 'POST': 
        enrollment.delete()
        messages.success(request, 'Inscrição cancelada com sucesso')
        return redirect('accounts:dashboard')
    # A inscrição só é cancelada quando o usuário aperta um botão na página, mas a opção de voltar
    #tem a tag <a></a>

    template_name = 'courses/undo_enrollment.html'
    context = {
        'course' : course,
        'enrollment' : enrollment
    }

    return render(request, template_name, context)

@login_required
@enrollment_required
def lessons(request, slug):
    course = request.course
    template_name = 'courses/lessons.html'
    lessons = course.release_lessons()
    
    if request.user.is_staff:
        lessons = course.course_lesson.all()
        
    context = {
        'course' : course,
        'lessons' : lessons
    }

    return render(request, template_name, context)

@login_required
@enrollment_required
def lesson(request, slug, pk):
    course = request.course
    lesson = get_object_or_404(Lesson, pk = pk, course = course)

    if not request.user.is_staff and not lesson.is_avaible():
        messages.error(request, 'Essa aula não está disponivel')
        return redirect('courses:lessons', slug=slug)
    
    template_name = 'courses/lesson.html'
    context = {
        'course' : course,
        'lesson' : lesson
    }

    return render(request, template_name, context)

@login_required
@enrollment_required
def material(request, slug, pk):
    course = request.course
    material = get_object_or_404(Material, pk = pk, lesson__course=course)
    lesson = material.lesson
    if not request.user.is_staff and not lesson.is_avaible():
        messages.error(request, 'Esse material não está disponível')
        return redirect('courses:lesson', slug=slug, pk=pk)
    if not material.is_embedded():
        return redirect(material.file.url)
    template_name= 'courses/material.html'
    context = {
        'course' : course,
        'material' : material,
        'lesson' : lesson
    }

    return render(request, template_name, context)

    

Simplemooc/courses/templates/courses/announcements.html
{%extends 'courses/course_dashboard.html'%}

{%block dashboard_content%}
{% for announcement in announcements %}
<div class="well">
	<h2><a href="{% url 'courses:show-announcement' course.slug announcement.pk%}">{{announcement}}</a></h2>
	{{announcement.content|linebreaks}}
	<p>
		<a href="#comments">
			<i class="far fa-comments"></i>
			{%with comments_count=announcement.announcements_comments.count%}
			{{comments_count}}
			Comentário{{comments_count|pluralize}}
			{%endwith%}
		</a>
	</p>
</div>
{%empty%}
<div class="well">
	<h2>Não há anúncios</h2>
</div>
{%endfor%}
{%endblock%}

Simplemooc/courses/templates/courses/course_dashboard.html
{%extends 'accounts/dashboard.html'%}
{%block breadcrumb%}
{{block.super}}
<li>/</li>
<li><a href="{%url 'courses:announcements' course.slug%}">{{course}}</a></li>
{%endblock%}

{%block menu-options%}
<li class="pure-menu-heading">{{course}}</li>
<li>
	<a href="{%url 'courses:lessons' course.slug%}">
		<i class="fas fa-camera"></i>Aulas e Materiais
	</a>
</li>

<li>
	<a href="#">
		<i class="fas fa-info-circle"></i>Informações
	</a>
</li>

<li>
	<a href="{% url 'courses:announcements' course.slug%}">
		<i class="fas fa-envelope"></i>Anúncios
	</a>
</li>

<li>
	<a href="#">
		<i class="fas fa-comments"></i>Forum de dúvidas
	</a>
</li>
{{block.super}}
{%endblock%}

Simplemooc/courses/templates/courses/details.html
{%extends 'base.html'%}
{%load static%}
{%block content%}
		<div class="splash">
			<div class="pure-g-r">
				<div class='pure-u-1'>
					<div class="l-box splash-text">
						<h1 class="splash-head">
							{{course}}
						</h1>
						<h2 class="splash-subhead">
							{{course.description}}
						</h2>
						<p>
								<a href="{% url 'courses:enrollment' course.slug%}" class="	pure-button primary-button">Inscreva-se</a>	
						</p>
					</div>
				</div>
			</div>
		</div>
		<div class="pure-g-r content-ribbon">
			<div class="pure-u-2-3">
				<div class="l-box">
					<h4 class="content-subhead">Sobre o curso</h4>
					<p>{{course.about|linebreaks}}</p>
				</div>
			</div>
			<div class="pure-u-1-3">
				<div class="l-box">
                    {% if course.image%}
                    <img src="{{course.image.url}}" alt="{{course}}"></a>
                    {% else%}
                    <img src="{%static 'img/placeholder.png'%}">
                    {%endif%}
				</div>
			</div>
		</div>
		<div class="pure-g-r content-ribbon" id="contato">
			<div class="pure-u-1">
				<h3>
					Tire suas dúvidas!
				</h3>
				{%if is_valid%}
				<p>Você enviou seu formulário com sucesso</p>
				{%endif%}
				<form action="#contato"class="pure-form pure-form-aligned" method="post">
					{%csrf_token%}
					<fieldset>
						{%for field in forms%}
							<div class="pure-control-group">
								{{field.label_tag}}
								{{field}}
							</div>
						{%endfor%}
						<div class="pure-controls">
							<button type='submit' class="pure-button pure-button-primary">Enviar</button>
						</div>
					</fieldset>
				</form>
			</div>
		</div>
{%endblock%}

Simplemooc/courses/templates/courses/index.html
{% extends 'base.html'%}
{%load static%}
{% block content%}
    {%for course in courses%}
    <div class="pure-gr content-ribbon">
        <div class="pure-u-1-3">
            <div class="l-box">
                <a href="{{course.get_absolute_url}}">
                    {% if course.image%}
                    <img src="{{course.image.url}}" alt="{{course}}"></a>
                    {% else%}
                    <img src="{%static 'img/placeholder.png'%}">
                    {%endif%}
            </div>
        </div>
        <div class="pure-u-2-3">
            <div class="l-box">
                <h4 class="content-subhead"><a href="{{course.get_absolute_url}}">
                	{{course}}
                </a></h4>

                {{course.description|linebreaks}}
            </div>
        </div>
    </div>
    {%empty%}
    <div class="pure-gr content-ribbon">
        <div class="pure-u-2-3">
            <div class="l-box">
                <p>Nenhum curso disponivel</p>
            </div>
        </div>
    </div>
    {%endfor%}
{% endblock %}

Simplemooc/courses/templates/courses/lesson.html
{%extends 'courses/course_dashboard.html'%}

{%block breadcrumb%}
{{block.super}}
<li>/</li>
<li><a href="{% url 'courses:lessons' course.slug%}">Aulas</a></li>
{%endblock%}

{%block dashboard_content%}
<div class="well">
	<h2>{{lesson}}</h2>
	{{lesson.description|linebreaks}}
	<table class="pure-table full">
		<thead>
			<tr>
				<th>
					Nome
				</th>
				<th>
					Ação
				</th>
			</tr>
		</thead>
		<tbody>
			{% for material in lesson.lesson_material.all %}
			<tr class="{% cycle '' 'pure-table-odd'%}"> <!-- Alterna entre estilos de um laço -->
				<td>
					{{material}}
				</td>
				<td>
					{%if material.is_embedded%}
					<a href="{%url 'courses:material' course.slug material.pk%}">
						<i class="fas fa-camera"></i>
						Acessar
					</a>
					{%else%}
					<a target="_blank" href="{{material.file.url}}">
						Baixar
					</a>
					{%endif%}
				</td>
			</tr>
			{%empty%}
			{%endfor%}
		</tbody>
	</table>
</div>
{%endblock%}

Simplemooc/courses/templates/courses/lessons.html
{%extends 'courses/course_dashboard.html'%}

{%block breadcrumb%}
{{block.super}}
<li>/</li>
<li><a href="{% url 'courses:lessons' course.slug%}">Aulas</a></li>
{%endblock%}

{%block dashboard_content%}
{%for lesson in lessons%}
	<div class="well">
		<h2><a href="{%url 'courses:lesson' course.slug lesson.pk%}">{{lesson}}</a></h2>
		{{lesson.description|truncatewords:'20'}}
		<br>
		<a href="{%url 'courses:lesson' course.slug lesson.pk%}">
			<i class="fas fa-eye"></i>
			Acessar aula
		</a>
	</div>
{%empty%}
	<div class="well">
		<h2>Não há aulas disponíveis</h2>
	</div>
{%endfor%}
{%endblock%}

Simplemooc/courses/templates/courses/mail.html
<p><strong>Nome:</strong>{{name}}</p>
<p><strong>Email:</strong>{{email}}</p>
{{message|linebreaks}}

Simplemooc/courses/templates/courses/material.html
{%extends 'courses/course_dashboard.html'%}

{%block breadcrumb%}
{{block.super}}
<li>/</li>
<li><a href="{% url 'courses:lessons' course.slug%}">Aulas</a></li>
{%endblock%}

{%block dashboard_content%}
	<div class="well">
		<h2>{{material}}</h2>
		{{material.embedded}}
		<p>
			<a href="{%url 'courses:lesson' course.slug lesson.pk%}">Voltar</a>
		</p>
	</div>
{%endblock%}

Simplemooc/courses/templates/courses/show_announcement.html
{%extends 'courses/course_dashboard.html'%}

{%block dashboard_content%}
	<div class="well">
		<h2>{{announcement.title}}</h2>
		{{announcement.content|linebreaks}}
	</div>
	<div class="well">
		<h4 id="comentarios">Comentários</h4>
		<a class="fright" href="#add_coment">Comentar</a>
		<hr>
		{%for comment in announcement.announcements_comments.all%}
		<p>
			<strong>{{comment.user}}</strong> comentou a {{comment.created_at|timesince}} atrás
			<br>
			{{comment.comment|linebreaks}}
		</p>
		<hr>
		{%empty%}
		<p>
			Não há comentários
		</p>
		{%endfor%}
		<form method="post" class="pure-form pure-form-stacked">
			{%csrf_token%}
			<fieldset>
				{{form.non_field_errors}}
				{%for field in form%}
				<div class="pure-control-group">
					{{field.label_tag}}
					{{field}}
					{{field.errors}}
				</div>
				{%endfor%}
				<div class="pure-controls">
					<button type="submit" class="pure-button pure-button-primary">Enviar</button>
				</div>
			</fieldset>
		</form>
	</div>
{%endblock%}

Simplemooc/courses/templates/courses/undo_enrollment.html
{%extends 'courses/course_dashboard.html'%}

{%block dashboard_content%}
	<form method="POST" >
		{%csrf_token%}
		<h3>Deseja realmente cancelar a inscrição desse curso?</h3>
		<div class="pure-controls">
			<button type="submit" class="pure-button button-error">Confirmar</button>
			<a href="{% url 'courses:announcements' course.slug%}" class="pure-button">Voltar</a>
		</div>
	</form>
{%endblock%}