Simplemooc/accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from . import views
from django.urls import path

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('entrar/', LoginView.as_view(template_name = 'accounts/login.html', next_page = None), name = 'login'),
    #A classe LoginView deve ser passada com o método .asView()
    #O método deverá ter atributos para um template customizado
    path('sair/', LogoutView.as_view(next_page = 'core:home'), name = 'logout'),
    #Mesmo que o anterior, mas não possui um template, apenas redireciona
    path('cadastro/', views.register, name='register'),
    path('editar/', views.edit, name='edit'),
    path('editar-senha/', views.edit_password, name='edit-password'),
    path('resetar-senha/', views.reset_password, name='reset'),
    path("confirmar-senha/<key>", views.reset_password_confirm, name="confirm-reset") 
    # Passa a chave de reset como atributo para a url 
]

Simplemooc/core/urls.py
from django.urls import path
from . import views #importa as views de core com o nome core_views(organização)

urlpatterns = (
    path('', views.home, name='home'), #chama a view home de core no caminho vazio
    path('contato/', views.contact, name='contact')
)

Simplemooc/forum/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from . import views as forum_views
from django.urls import path

urlpatterns = [
    path('', forum_views.index, name='index'),
    path(r'tag/<tag>', forum_views.index, name='index_tagged'),
    path(r'topico/<slug:slug>', forum_views.thread, name='thread'),
    path(r'respostas/<int:pk>/correta', forum_views.reply_correct, name='reply-correct'),
    path(r'respostas/<int:pk>/incorreta', forum_views.reply_incorrect, name='reply-incorrect'),
]

Simplemooc/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from .core import urls as core_urls
from .courses import urls as course_urls
from .accounts import urls as accounts_urls
from .forum import urls as forum_urls

urlpatterns = [
    path('admin/', admin.site.urls),

    path(r'', include((core_urls, 'core'), namespace = 'core')),
    path(r'cursos/', include((course_urls, 'courses'), namespace = 'courses')),
    path(r'conta/', include((accounts_urls, 'accounts'), namespace = 'accounts')),
    path(r'forum/', include((forum_urls, 'forum'), namespace = 'forum'))
]

Simplemooc/core/views.py
from django import http
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

def home(request):
    template_name = 'home.html',
    return render(request, template_name) #retorna o template e seu conteúdo

def contact(request):
    template_name = 'contact.html'
    return render(request, template_name)

Simplemooc/core/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Simple MOOC - Uma simples plataforma de ensino a distância" />
    <title>Simple MOOC</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.3.0/pure-min.css">
    <link rel="stylesheet" href="https://unpkg.com/purecss@2.0.6/build/pure-min.css" integrity="sha384-Uu6IeWbM+gzNVXJcM9XV3SohHtmWE+3VGi496jvgX1jyvDTXfdK+rfZc8C1Aehk5" crossorigin="anonymous">
    <link rel="stylesheet" type = 'text/css' href="{% static 'css/styles.css' %}" />

    <script src="https://kit.fontawesome.com/fb453dd15c.js" crossorigin="anonymous"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"> </script>

    {% block scripts %}
    {% endblock %}

    <style type="text/css">
        .button-error {
            background: rgb(202, 60, 60);
            /* this is a maroon */
        }
        ul.breadcrumb{
            list-style-type: none;
            padding : 10px 16px;
        }

        ul.breadcrumb li{
            display: inline;
        }

        .well{
            border: 1px solid #ddd;
            padding: 0em 1em 1em 1em;
            margin: 1em;
        }

        * {
            -webkit-box-sizing: border-box;
            -moz-box-sizing: border-box;
            box-sizing: border-box;
        }
        body {
            margin: 0 auto;
            line-height: 1.7em;
        }
        .l-box {
            padding: 1em;
        }
        .header {
            margin: 0 0;
        }
        .header .pure-menu {
            padding: 0.5em;
        }
        .header .pure-menu li a:hover,
        .header .pure-menu li a:focus {
            background: none;
            border: none;
            color: #aaa;
        }
        body .primary-button {
            background: #02a6eb;
            color: #fff;
        }
        .splash {
            margin: 2em auto 0;
            padding: 3em 0.5em;
            background: #eee;
        }
        .splash .splash-head {
            font-size: 300%;
            margin: 0em 0;
            line-height: 1.2em;
        }
        .splash .splash-subhead {
            color: #999;
            font-weight: 300;
            line-height: 1.4em;
        }
        .splash .primary-button {
            font-size: 150%;
        }
        .content .content-subhead {
            color: #999;
            padding-bottom: 0.3em;
            text-transform: uppercase;
            margin: 0;
            border-bottom: 2px solid #eee;
            display: inline-block;
        }
        .content .content-ribbon {
            margin: 3em;
            border-bottom: 1px solid #eee;
        }
        .ribbon {
            background: #eee;
            text-align: center;
            padding: 2em;
            color: #999;
        }
        .ribbon h2 {
            display: inline;
            font-weight: normal;
        }
        .footer {
            background: #111;
            color: #666;
            text-align: center;
            padding: 1em;
            font-size: 80%;
        }
        
        ul.breadcrumb {
            padding: 10px 16px;
            list-style: none;
        }
        
        header {
            margin: 0 0;
        }
        
        .header .pure-menu {
            padding: 0.5em;
            background-color: #2d3e50;
        }
        
        .header .pure-menu a {
            color: #fff;
        }
        
        .header .pure-menu li a:hover,
        .header .pure-menu li a:focus {
            background: none;
            border: none;
            color: #AECFE5;
        }
        
        .header .pure-menu-heading {
            float: left;
        }
        
        .header ul {
            float: right;
        }
        
        .home-menu{
            padding: 0.5em;
            text-align: left;
            box-shadow: 0 1px 1px rgba(0,0,0, 0.10);
        }
        
        .home-menu.pure-menu-open {
            background: #2d3e50;
        }
        
        .home-menu a {
            color: #6FBEF3;
        }
        
        .home-menu li a:hover,
        .home-menu li a:focus {
            background: none;
            border: none;
            color: #AECFE5;
        }
        .pagination {
            display: inline-block;
            text-align: center;
        }

        .pagination a {
            color: black;
            float: left;
            padding: 8px 16px;
            text-decoration: none;
            border: 1px solid #ddd;
        }

        .pagination .active a {
            background-color: #f5f5f5;
            display: inline-block;
        }
    </style>

</head>
<body>
    <div class="header">
        <div class="home-menu pure-menu pure-menu-open pure-menu-horizontal pure-menu-fixed">
            <a class="pure-menu-heading pure-menu-link" href="{% url 'core:home'%}">SIMPLE MOOC</a>
            <ul class="pure-menu-list">
                <li class="pure-menu-item"><a class="pure-menu-link" href="{% url 'courses:index'%}">Cursos</a></li>
                <li class="pure-menu-item"><a class="pure-menu-link" href="{% url 'core:contact'%}">Contato</a></li>
                <li class="pure-menu-item"><a class="pure-menu-link" href="{% url 'forum:index'%}">Fóruns</a></li>

                {%if user.is_authenticated%} <!-- Verifica se o usuário é autenticado, ou seja, não anônimo
                                                  OBS : Não é necessário adicionar ao contexto -->
                <li class="pure-menu-item"><a class="pure-menu-link" href="{% url 'accounts:dashboard'%}">Painel</a></li>
                <li class="pure-menu-item"><a class="pure-menu-link" href="{% url 'accounts:logout'%}">Sair</a></li>

                {%else%}

                <li class="pure-menu-item"><a class="pure-menu-link" href="{% url 'accounts:login'%}">Entrar</a></li>
                <li class="pure-menu-item"><a class="pure-menu-link" href="{% url 'accounts:register'%}">Cadastro</a></li>

                {%endif%}
            </ul>
        </div>
    </div>
<div class="content">
    <div class="content">
        {%if messages%}
        <div class="pure-g-r content-ribbon">
            <aside class="pure-u-1">
                {%for message in messages%}
                <p>{{message}}</p>
                {%endfor%}
            </aside>
        </div>
        {%endif%}
        {%block content%}
        {% endblock %}
    </div>
    <div class="footer">
        Simple MOOC - Uma simples plataforma de ensino a distância
    </div>
</div>
<script src="http://yui.yahooapis.com/3.12.0/build/yui/yui-min.js"></script>
</body>
</html>

Simplemooc/core/templates/contact.html
{% extends 'base.html' %}
{% block content %}
    <div class="splash">
        <div class="pure-g-r">
            <div class="pure-u-1">
                <div class="l-box splash-text">
                    <h1 class="splash-head">
                        Fale conosco
                    </h1>
                    <h2>
                        carlosfelipe.st28@gmail.com
                    </h2>
                </div>
            </div>
        </div>
    </div>
    </div>
{% endblock content %}

Simplemooc/core/templates/home.html
{% extends 'base.html' %}
{% block content %}
    <div class="content">
        <div class="splash">
            <div class="pure-g-r">
                <div class="pure-u-1">
                    <div class="l-box splash-text">
                        <h1 class="splash-head">
                            Uma Simples Plataforma de Ensino a Distância
                        </h1>
                        <h2 class="splash-subhead">
                            O Simple MOOC visa simplificar o ensino a distância, provendo ferramentas objetivas e de fácil uso para cursos a distância.
                        </h2>
                        <p>
                            <a href="#" class="pure-button primary-button">Saiba mais</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="pure-g-r content-ribbon">
            <div class="pure-u-2-3">
                <div class="l-box">
                    <h4 class="content-subhead">Vídeo-aulas e materiais digitais</h4>
                    <h3>Publique suas aulas</h3>
                    <p>
                        O Simple MOOC tem um sistema simples e prático para que o professor disponibilize vídeo-aulas e materiais digitais como: pdf's, slides, imagens ...
                    </p>
                </div>
            </div>
            <div class="pure-u-1-3">
                <div class="l-box">
                    <img src="https://placehold.it/400x250"
                         alt="Vídeo aulas e materiais digitais.">
                </div>
            </div>
        </div>
        <div class="pure-g-r content-ribbon">
            <div class="pure-u-1-3">
                <div class="l-box">
                    <img src="https://placehold.it/400x250"
                         alt="Fórum de Dúvidas">
                </div>
            </div>
            <div class="pure-u-2-3">
                <div class="l-box">
                    <h4 class="content-subhead">Fórum de Dúvidas</h4>
                    <h3>Interaja com seus Alunos</h3>
                    <p>
                        No Simple MOOC você pode ter seu próprio sistema de fórum para que seus alunos possam interagir com você e com os outros alunos
                    </p>
                </div>
            </div>
        </div>
        <div class="pure-g-r content-ribbon">
            <div class="pure-u-2-3">
                <div class="l-box">
                    <h4 class="content-subhead">Exercícios</h4>
                    <h3>Crie exercícios para avaliar seus alunos</h3>
                    <p>
                        Você pode criar exercícios para que os alunos possam ser avaliados e todo o controle de notas e resolução dos exercícios é controlado pela plataforma, facilitando sua vida
                    </p>
                </div>
            </div>
            <div class="pure-u-1-3">
                <div class="l-box">
                    <img src="https://placehold.it/400x250"
                         alt="Exercícios">
                </div>
            </div>
        </div>
        <div class="pure-g-r content-ribbon">
            <div class="pure-u-1-3">
                <div class="l-box">
                    <img src="https://placehold.it/400x250"
                         alt="Mural de Avisos">
                </div>
            </div>
            <div class="pure-u-2-3">
                <div class="l-box">
                    <h4 class="content-subhead">Mural de Avisos</h4>
                    <h3>Envie anúncios diretamente para os alunos</h3>
                    <p>
                        Organize os avisos do seu curso de forma fácil e simples.
                    </p>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}