Simplemooc/accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from . import views
from django.urls import path

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('entrar/', LoginView.as_view(template_name = 'accounts/login.html', next_page = None), name = 'login'),
    #A classe LoginView deve ser passada com o método .asView()
    #O método deverá ter atributos para um template customizado
    path('sair/', LogoutView.as_view(next_page = 'core:home'), name = 'logout'),
    #Mesmo que o anterior, mas não possui um template, apenas redireciona
    path('cadastro/', views.register, name='register'),
    path('editar/', views.edit, name='edit'),
    path('editar-senha/', views.edit_password, name='edit-password'),
    path('resetar-senha/', views.reset_password, name='reset'),
    path("confirmar-senha/<key>", views.reset_password_confirm, name="confirm-reset") 
    # Passa a chave de reset como atributo para a url 
]

Simplemooc/courses/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from . import views

urlpatterns = [
    path('', views.index, name = 'index'),
   #path('<int:pk>', views.details, name = 'details') #regular expression para receber uma url com base na pk de um curso
    path('<slug:slug>', views.details, name = 'details'),
    path('<slug:slug>/inscricao', views.enrollments, name='enrollment'),
    path('<slug:slug>/anuncios', views.announcements, name='announcements'),
    path('<slug:slug>/cancelar-inscricao', views.undo_enrollment, name = 'undo-enrollment'),
    path('<slug:slug>/anuncios/<int:pk>', views.show_announcement, name = 'show-announcement'),
    path('<slug:slug>/aulas', views.lessons, name = 'lessons'),
    path('<slug:slug>/aulas/<int:pk>', views.lesson, name = 'lesson'),
    path('<slug:slug>/aulas/materiais/<int:pk>', views.material, name = 'material')
]

Simplemooc/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from .core import urls as core_urls
from .courses import urls as course_urls
from .accounts import urls as accounts_urls
from .forum import urls as forum_urls

urlpatterns = [
    path('admin/', admin.site.urls),

    path(r'', include((core_urls, 'core'), namespace = 'core')),
    path(r'cursos/', include((course_urls, 'courses'), namespace = 'courses')),
    path(r'conta/', include((accounts_urls, 'accounts'), namespace = 'accounts')),
    path(r'forum/', include((forum_urls, 'forum'), namespace = 'forum'))
]

Simplemooc/accounts/models.py
import re

from django.db import models
from django.core.validators import RegexValidator
from django.contrib.auth.models import (AbstractBaseUser, PermissionsMixin, 
UserManager) # Classe de utilitários 
from django.conf import settings
from Simplemooc.courses.models import Course

class User(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(
        'Nome de usuário', max_length=30, unique=True, #O unique = True é necessário
        validators= [RegexValidator(re.compile('^[\w.@+-]+$'), 'O nomes de usuário inserido é inválido')]
    ) 
    email = models.EmailField('Email', unique=True)
    name = models.CharField('Nome', max_length=100)
    is_active = models.BooleanField('Está ativo?', blank=True, default=True)
    is_staff = models.BooleanField('É da equipe?', blank=True, default=False)
    date_joined = models.DateTimeField('Data de entrada', auto_now_add=True)

    objects = UserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email'] #Lista com atributos obrigatórios

    def __str__(self): # Retorna um nome para o objeto
        return self.name or self.username
    
    def get_short_name(self):
        return self.username
    
    def get_full_name(self):
        return self.name

    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'

class PasswordReset(models.Model):

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
     verbose_name='Usuário') # Chave estrangeira, referenciando o caminho do usuário padrão
    key = models.CharField('Chave', unique=True, max_length=100) # Atributo principal
    created_at = models.DateTimeField('Criado em', auto_now_add=True, blank=True) 
    confirmed = models.BooleanField('Confirmado?', default=False, blank=True)

    def __str__(self):
        return '{0} - {1}'.format(self.user, self.key)
    
    class Meta:
        verbose_name = 'Nova Senha'
        verbose_name = 'Novas Senhas'
        ordering = ['created_at']

class Enrollments(models.Model):
    STATUS_CHOICES = (
        (0, 'Pendente'),
        (1, 'Aprovado'),
        (2, 'Cancelado'),
        (3, 'Indisponível')
    )

    #Esses dois atributos referenciam as duas classes pai, cursos e usuários
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, 
    related_name = 'enrollments', verbose_name='Usuário')
    course = models.ForeignKey(Course, on_delete=models.CASCADE, 
    related_name='enrollments', verbose_name='Curso')

    #Inteiro representando opções
    status = models.IntegerField('Situação', choices=STATUS_CHOICES, default=0, blank=True)

    created_at = models.DateTimeField('Criado em', auto_now_add=True, blank=True)

    updated_at = models.DateTimeField('Atualizado em', auto_now=True, blank=True)

    class Meta:
        verbose_name = 'Inscrição'
        verbose_name_plural = 'Inscrições'
        unique_together = (('user', 'course'),)
        #Essa instrução define que não podera haver o mesmo usuário inscrito no mesmo curso duas vezes

Simplemooc/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from Simplemooc.core.mail import send_mail_template
from .utils import generate_hash_key
from .models import PasswordReset
from django.forms.widgets import PasswordInput
#Essas duas linhas são necessárias já que há um modelo personalizado padrão para usuário
User = get_user_model()

class RegisterForm(forms.ModelForm):

    email = forms.EmailField(label = 'E-Mail')
    password1 = forms.CharField(label='Senha', widget=PasswordInput)
    password2 = forms.CharField(label='Confirmação de senha', widget=PasswordInput)

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'], code='password_mismatch'
                )
        return password2

    def save(self, commit=True): # Método para salvar o email do usuário separadamente(não padrão)
        user = super(RegisterForm, self).save(commit = False)

        if commit:
            user.save()
        return user

    class Meta:
        model = User
        fields = ['username', 'email']

class EditAccountForm(forms.ModelForm):

    # O método clean_email não é necessário, já que o form é custom

    class Meta:
        model = User
        fields = ['username', 'name', 'email']

class ResetPassword(forms.Form):

    email = forms.EmailField(label='E-Mail')

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email = email).exists():
            return email
        raise forms.ValidationError('Não foi encontrado usuário com este email')
    
    def save(self):        
        user = User.objects.get(email = self.cleaned_data['email'])
        key = generate_hash_key(user.username) # Envia o nome de usuário como argumento
        reset = PasswordReset(key = key, user = user) 
        reset.save()

        template_name = 'accounts/email/password_reset.html'
        subject = 'Criar nova senha no SimpleMOOC'
        context = {
            'reset' : reset
        }

        send_mail_template(subject, template_name, context, [user.email]) # Envia um email para o
        #usuário que deseja resetar a senha, ainda está no email do terminal


#O seguinte trecho é utilizado se o usuário for o padrão do Django

'''class RegisterForm(UserCreationForm):

    email = forms.EmailField(label = 'E-Mail') #Adiciona email como field do form

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists(): # Verifica se o email ja está cadastrado
            raise forms.ValidationError('Email já cadastrado!') # Retorna um erro se o email ja estiver cadastrado
        
        return email

    def save(self, commit=True): # Método para salvar o email do usuário separadamente(não padrão)
        user = super(RegisterForm, self).save(commit = False) # Não salva o usuário padrão
        user.email = self.cleaned_data['email'] # Atribui o email ao usuário

        if commit:
            user.save()
        
        return user

class EditAccountForm(forms.ModelForm):

    def clean_email(self):
        email = self.cleaned_data['email']
        query_set = User.objects.filter(email=email).exclude(pk = self.instance.pk)
        #Verifica se o email ja foi utilizado, com exceção ao do usuário
        
        if query_set.exists(): #O .exists é necessário
            raise forms.ValidationError('Este email ja está sendo utilizado')
        
        return email

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']'''

Simplemooc/accounts/views.py
from django.contrib.auth.forms import PasswordChangeForm, SetPasswordForm
from django.shortcuts import get_object_or_404, redirect, render
#from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from Simplemooc.accounts.models import PasswordReset
from Simplemooc.accounts.utils import generate_hash_key
from Simplemooc.courses.models import Enrollments
from .forms import EditAccountForm, RegisterForm, ResetPassword
from django.conf import settings

User = get_user_model()

@login_required #Redireciona para o login se não houver usuário logado
def dashboard(request):
    template_name = 'accounts/dashboard.html'
    enrollments = Enrollments.objects.filter(user = request.user)
    context = {
        'enrollments' : enrollments
    }
    return render(request, template_name, context)

def register(request):
    template_name = 'accounts/register.html'

    if request.method == 'POST':
        #form = UserCreationForm(request.POST)
        form = RegisterForm(request.POST) #Utiliza do form custom com email
        if form.is_valid(): #Verifica se o form é valido
            user = form.save() #Salva os dados em um objeto da tabela

            # Esse trecho da conflito com um model personalizado para usuário, ao invés disso, var direto para login
            '''user = authenticate(
                username = user.username, password = form.cleaned_data['password1']
            )#Autentica o usuário'''
            
            login(request, user)#Automaticamente loga o usuário após o cadastro
            return redirect('core:home') #Redireciona para a página inicial
    else:
        #form = UserCreationForm()
        form = RegisterForm() 

    context = {
        'form' : form #Classe simples de criação de usuários do Django
    }

    return render(request, template_name, context)

def reset_password(request):
    template_name = 'accounts/reset.html'
    context = {}
    form = ResetPassword(request.POST or None) # Mesma coisa que os outros, só que com menos linhas
    if form.is_valid():
        form.save()
        context['sucess'] = True
    context['form'] = form
    return render(request, template_name, context)

def reset_password_confirm(request, key):
    template_name = 'accounts/confirm_reset.html'
    context = {}
    reset = get_object_or_404(PasswordReset, key = key) # Verifica se há uma solicitação existente
    form = SetPasswordForm(user=reset.user, data=request.POST or None) # Utiliza do form padrão do Django para resetar senha
    if form.is_valid():
        form.save()
        context['sucess'] = True
    context['form'] = form
    return render(request, template_name, context)

@login_required
def edit(request):
    template_name = 'accounts/edit.html'
    context = {}

    if request.method == 'POST':
        form = EditAccountForm(request.POST, instance = request.user)
        if form.is_valid():
            form.save()
            form = EditAccountForm(instance = request.user)
            messages.success(request,'Dados da conta alterados com sucesso')
    
    else:
        form = EditAccountForm(instance = request.user)

    context['form'] = form

    return render(request, template_name, context)

@login_required
def edit_password(request):
    template_name = 'accounts/edit_password.html'
    context = {}

    if request.method == 'POST':
        form = PasswordChangeForm(data = request.POST, user=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Senha alterada com sucesso')

    else:
        form = PasswordChangeForm(user=request.user)
    
    context['form'] = form

    return render(request, template_name, context)

Simplemooc/accounts/templates/accounts/confirm_reset.html
{%extends 'base.html'%}
{%block content%}
<div class="pure-g-r content-ribbon">
	<div class="pure-u-1">
		{%if sucess%}
		<p>Senha alterada com sucesso</p>
		{%else%}
		<h2>Informe sua nova senha</h2>
		<form class="pure-form pure-form-aligned" method='post'>
			{%csrf_token%}
			<fieldset>
				{{form.non_field_errors}} <!-- Determina erros de autenticação, não de impropriação -->
				{%for field in form%}
					<div class="pure-control-group">
						{{field.label_tag}}
						{{field}}
						{{field.errors}}
					</div>
				{%endfor%}
				<div  class="pure-controls">
					<button class="pure-button pure-button-primary" type="submit">Enviar</button>
				</div>
			</fieldset>
		</form>
		{%endif%}
	</div>
</div>
{%endblock%}

Simplemooc/accounts/templates/accounts/dashboard.html
{%extends 'base.html'%}

{%load course_tags%}
{%block content%}
<div class="pure-g-r content-ribbon">
	<div class="pure-u-1-3">
		<ul class="breadcrumb">
			{%block breadcrumb%}
			<li ><a href="{%url 'accounts:dashboard'%}">Meu painel</a></li>
			{%endblock%}
		</ul>
		<div class="pure-menu pure-menu-open">
			<ul>
				<li class="pure-menu-heading">Bem vindo {{user}}</li>
				{%block menu-options%}
				{%my_courses user%}
				<li><a class="pure-menu-heading">Minha Conta</a></li>
				<li><a href="{%url 'accounts:edit'%}"><i class="fas fa-cog"></i>Editar Conta</a></li>
				<li><a href="{%url 'accounts:edit-password'%}"><i class="fas fa-lock"></i>Editar Senha</a></li>
				{%endblock%}
			</ul>
		</div>
	</div>
	<div class="pure-u-2-3">
		<div class="inner">
			{%block dashboard_content%}
			<h2>Meus cursos : </h2>
			{%for enrollment in enrollments%}
			<div class="well">
				<h3>{{enrollment.course}} ({{enrollment.course.start_date|date:'d/M/Y'|default:'Data não informada'}})</h3>
				{{enrollment.course.description|linebreaks}}
				<div class="pure-controls">
					<a href="{% url 'courses:announcements' enrollment.course.slug%}" class="pure-button pure-button-primary"> Acessar </a>
					<a href="{% url 'courses:undo-enrollment' enrollment.course.slug%}" class="pure-button button-error"> Cancelar </a>
				</div>
			</div>
			{%empty%}
			<aside class="pure-u-1">Não há cursos inscritos</aside>
			{%endfor%}
			{%endblock%}
		</div>
	</div>
</div>
{%endblock%}

Simplemooc/accounts/templates/accounts/edit.html
{% extends 'accounts/dashboard.html' %}
{%block breadcrumb%}
	{{block.super}}
	<li>/</li>
	<li><a href="{%url 'accounts:edit'%}">Editar Conta</a></li>
{%endblock%}

{%block dashboard_content%}
	<form class="pure-form pure-form-stacked" method="post">
		{% csrf_token %}
		{%if sucess%}
		<p>Os dados foram alterados com sucesso</p>
		{%endif%}
		<fieldset>
			{{form.non_field_errors}}
			{%for field in form%}
			<div class="pure-control-group">
				{{field.label_tag}}
				{{field}}
				{{field.errors}}
			</div>
			{%endfor%}
			<div class="pure-controls">
				<button class="pure-button pure-button-primary" type="submit">Salvar</button>
			</div>
		</fieldset>
	</form>
{%endblock%}

Simplemooc/accounts/templates/accounts/edit_password.html
{% extends 'accounts/dashboard.html' %}
{%block breadcrumb%}
	{{block.super}}
	<li>/</li>
	<li><a href="{%url 'accounts:edit-password'%}">Editar Senha</a></li>
{%endblock%}

{%block dashboard_content%}
	<form class="pure-form pure-form-stacked" method="post">
		{% csrf_token %}
		{%if sucess%}
		<p>A senha foi alterada com sucesso</p>
		{%endif%}
		<fieldset>
			{{form.non_field_errors}}
			{%for field in form%}
			<div class="pure-control-group">
				{{field.label_tag}}
				{{field}}
				{{field.errors}}
			</div>
			{%endfor%}
			<div class="pure-controls">
				<button class="pure-button pure-button-primary" type="submit">Salvar</button>
			</div>
		</fieldset>
	</form>
{%endblock%}

Simplemooc/accounts/templates/accounts/login.html
{%extends 'base.html'%}
{%block content%}
<div class="pure-g-r content-ribbon">
	<div class="pure-u-1">
		<h2>Informe seus dados</h2>
		<form class="pure-form pure-form-aligned" method='post'>
			{%csrf_token%}
			<fieldset>
				{{form.non_field_errors}} <!-- Determina erros de autenticação, não de impropriação -->
				{%for field in form%}
					<div class="pure-control-group">
						{{field.label_tag}}
						{{field}}
						{{field.errors}}
					</div>
				{%endfor%}
				<div  class="pure-controls">
					<button class="pure-button pure-button-primary" type="submit">Entrar</button>
				</div>
			</fieldset>
			<p>
				Não é cadastrado? <a href="{%url 'accounts:register'%}">Cadastre-se</a> <br>
				Esqueceu a senha? <a href="{%url 'accounts:reset'%}">Nova senha</a> <br>
			</p>
		</form>
	</div>
</div>
{%endblock%}

Simplemooc/accounts/templates/accounts/register.html
{%extends 'base.html'%}
{%block content%}
<div class="pure-g-r content-ribbon">
	<div class="pure-u-1">
		<h2>Informe seus dados para o cadastro</h2>
		<form class="pure-form pure-form-aligned" method='post'>
			{%csrf_token%}
			<fieldset>
				{{form.non_field_errors}} <!-- Determina erros de autenticação, não de impropriação -->
				{%for field in form%}
					<div class="pure-control-group">
						{{field.label_tag}}
						{{field}}
						{{field.errors}}
					</div>
				{%endfor%}
				<div  class="pure-controls">
					<button class="pure-button pure-button-primary" type="submit">Entrar</button>
				</div>
			</fieldset>
			<p>
				Ja está cadastrado? <a href="{% url 'accounts:login'%}">Login</a> <br>
			</p>
		</form>
	</div>
</div>
{%endblock%}

Simplemooc/accounts/templates/accounts/reset.html
{%extends 'base.html'%}
{%block content%}
<div class="pure-g-r content-ribbon">
	<div class="pure-u-1">
		{%if sucess%}
		<p>Um email foi enviado para você</p>
		{%else%}
		<h2>Informe seu email</h2>
		<form class="pure-form pure-form-aligned" method='post'>
			{%csrf_token%}
			<fieldset>
				{{form.non_field_errors}} <!-- Determina erros de autenticação, não de impropriação -->
				{%for field in form%}
					<div class="pure-control-group">
						{{field.label_tag}}
						{{field}}
						{{field.errors}}
					</div>
				{%endfor%}
				<div  class="pure-controls">
					<button class="pure-button pure-button-primary" type="submit">Enviar</button>
				</div>
			</fieldset>
		</form>
		{%endif%}
	</div>
</div>
{%endblock%}