Simplemooc/core/urls.py
from django.urls import path
from . import views #importa as views de core com o nome core_views(organização)

urlpatterns = (
    path('', views.home, name='home'), #chama a view home de core no caminho vazio
    path('contato/', views.contact, name='contact')
)

Simplemooc/forum/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from . import views as forum_views
from django.urls import path

urlpatterns = [
    path('', forum_views.index, name='index'),
    path(r'tag/<tag>', forum_views.index, name='index_tagged'),
    path(r'topico/<slug:slug>', forum_views.thread, name='thread'),
    path(r'respostas/<int:pk>/correta', forum_views.reply_correct, name='reply-correct'),
    path(r'respostas/<int:pk>/incorreta', forum_views.reply_incorrect, name='reply-incorrect'),
]

Simplemooc/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from .core import urls as core_urls
from .courses import urls as course_urls
from .accounts import urls as accounts_urls
from .forum import urls as forum_urls

urlpatterns = [
    path('admin/', admin.site.urls),

    path(r'', include((core_urls, 'core'), namespace = 'core')),
    path(r'cursos/', include((course_urls, 'courses'), namespace = 'courses')),
    path(r'conta/', include((accounts_urls, 'accounts'), namespace = 'accounts')),
    path(r'forum/', include((forum_urls, 'forum'), namespace = 'forum'))
]

Simplemooc/forum/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
# Create your models here.

from taggit.managers import TaggableManager

class Thread(models.Model):
    title = models.CharField('Título', max_length=100)
    slug = models.SlugField('Identificador', max_length=100, unique=True)
    body = models.TextField('Conteúdo')
    views = models.IntegerField('Visualizações', blank=True, default=0)
    answers = models.IntegerField('Respostas', blank=True, default=0)

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, related_name='user_thread', null=True)

    created_at = models.DateTimeField('Criado em ', auto_now_add=True, blank=True)
    updated_at = models.DateTimeField('Atualizado em', auto_now=True, blank = True)

    tags = TaggableManager()

    def __str__(self):
        return self.title
        
    def get_absolute_url(self):
        return reverse("forum:thread", kwargs={"slug": self.slug}) # Retorna url com o endereço da view, args, e kwargs
    
    
    class Meta:
        verbose_name = 'Tópico'
        verbose_name_plural = 'Tópicos'
        ordering = ['updated_at']

class Reply(models.Model):
    reply = models.TextField('Resposta')
    correct = models.BooleanField('Correto?', blank = True, default=False)

    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, related_name='user_reply', null=True)
    thread = models.ForeignKey(Thread, on_delete=models.CASCADE, related_name='thread_reply')

    created_at = models.DateTimeField('Criado em', blank=True, auto_now_add=True)
    updated_at = models.DateTimeField('Atualizado em', blank=True, auto_now=True)

    def __str__(self):
        return '{0}/{1}'.format(self.author, self.created_at)

    class Meta:
        verbose_name = 'Resposta'
        verbose_name_plural = "Respostas"
        ordering = ['-correct', 'updated_at'] # Booleans são organizados de negativo em positivo

def post_save_reply(created, instance, **kwargs):
    instance.thread.answers = instance.thread.thread_reply.count()
    instance.thread.save()
    if instance.correct:
        instance.thread.thread_reply.exclude(pk = instance.pk).update(correct = False) # Atualiza sem chamar
        #o método post_save novamente

def post_delete_reply(instance, **kwargs):
    instance.thread.answers = instance.thread.thread_reply.count()
    instance.thread.save()

models.signals.post_save.connect(post_save_reply, sender = Reply, dispatch_uid='post_save_reply')

models.signals.post_delete.connect(post_delete_reply, sender = Reply, dispatch_uid='post_delete_reply')

Simplemooc/forum/forms.py
from django import forms
from .models import Reply

class ReplyForm(forms.ModelForm):
    class Meta:
        model = Reply
        fields = ['reply']

Simplemooc/forum/views.py
from typing import Any
from django.db.models import query
from django.contrib import messages
from django.http.response import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import TemplateView, View, ListView, DetailView
from taggit.models import Tag

from Simplemooc.forum.models import Reply, Thread
from .forms import ReplyForm

import json

# Create your views here.

'''class ForumView(View):
    # template_name = 'forum/index.html'
    def get(self, requests, *args, **kwargs):
        return render(self.request, 'forum/index.html')'''

class ForumView(ListView):
    model = Thread
    paginate_by = 2
    template_name = 'forum/index.html'

    def get_queryset(self):
        queryset = Thread.objects.all()
        order = self.request.GET.get('order', '')

        if order == 'views':
            queryset = queryset.order_by('-views')

        elif order == 'answers':
            queryset = queryset.order_by('-answers')

        tag = self.kwargs.get('tag', None) # Pega um parâmetro nomeado do template

        if tag:
            queryset = queryset.filter(tags__slug__in = [tag]) # Filtra os resultados com base na tag
        return queryset

    def get_context_data(self, **kwargs):
        context = super(ForumView, self).get_context_data(**kwargs)
        context['tags'] = Thread.tags.all()
        return context

class ThreadView(DetailView):
    template_name = 'forum/thread.html'
    model = Thread
    
    def get(self, request, *args, **kwargs):
        response = super(ThreadView, self).get(request, *args, **kwargs)
        if request.user.is_authenticated or request.user != self.object.user:
            self.object.views = self.object.views + 1
            self.object.save()
        return response

    def get_context_data(self, **kwargs: Any):
        context =  super(ThreadView, self).get_context_data(**kwargs)
        context['tags'] = Thread.tags.all()
        context['form'] = ReplyForm(self.request.POST or None)
        return context
    
    def post(self, request, *args:Any, **kwargs:Any):
        if not request.user.is_authenticated:
            messages.error(request, 'Você precisa estar logado para enviar respostas')
            return redirect(self.request.path)

        self.object = self.get_object()
        context = self.get_context_data(object = self.object)
        form = context['form']

        if form.is_valid():
            reply = form.save(commit=False) # Preenche os campos sem salvar, não há usuário definido, então
            #é necessário
            reply.author = self.request.user
            reply.thread = self.object
            reply.save()
            messages.success(request, 'Resposta enviada com sucesso')
            context['form'] = ReplyForm()

        return render(request, 'forum/thread.html', context)

class ReplyCorrectView(View):

    correct = True
    
    def get(self, request, pk):
        reply = get_object_or_404(Reply, pk = pk)
        reply.correct = self.correct
        reply.save()
        message = "Resposta atualizada com sucesso"
        if request.accepts("application/json"):
            data = {'sucess' : True, 'message' : message}
            return HttpResponse(json.dumps(data))
        
        else:
            messages.success(request, message)
            return redirect(reply.thread.get_absolute_url())

index = ForumView.as_view()
thread = ThreadView.as_view()
reply_correct = ReplyCorrectView.as_view()
reply_incorrect = ReplyCorrectView.as_view(correct = False)

def forumView(request, slug = None):
    template_name = 'forum/index.html'
    context = {}

    context['tags'] = Thread.tags.all()

    posts = Thread.objects.all()

    order = request.GET.get('order', '')

    if order == 'views':
        posts = posts.order_by('views')
    
    elif order == 'answers':
        posts = posts.order_by('answers')

    if slug:
        posts = posts.filter(tags__slug__in = [slug])
    
    context['posts'] = posts
    
    return render(request, template_name, context)

Simplemooc/forum/templates/forum/index.html
{%extends 'base.html'%}
{%block content%}
<div class="pure-g-r content-ribbon">
	<div class="pure-u-1">
		<ul class="breadcrumb">
			<li><a href="{% url 'core:home' %}">Início</a></li>
			<li>/</li>
			<li><a href="{% url 'forum:index' %}">Página de discussões</a></li>
		</ul>
	</div>
	<div class="pure-u-1-3">
		<div class="pure-menu pure-menu-open">
			<ul>
				<li class="pure-menu-heading">Tópicos : </li>
				<li><a href="?order=updated_at"><i class="fas fa-sync"></i> Mais recentes</a></li>
				<li><a href="?order=views"><i class="fas fa-eye"></i> Mais visualizados</a></li>
				<li><a href="?order=answers"><i class="fas fa-comments"></i> Mais comentados</a></li>

				<li class="pure-menu-heading">Tags : </li>
				{% for tag in tags %}
				<li><a href="{% url 'forum:index_tagged' tag.slug%}"><i class="fas fa-tag"> {{tag}}</i></a></li>
				{% endfor %}
			</ul>
		</div>
	</div>
		<div class="pure-u-2-3">
			{% for thread in object_list %}
			<div class="well">
				<h3><a href="{{thread.get_absolute_url}}">{{thread.title}}</a></h3>
				<h5>
					Criado por {{thread.user}} | {{thread.views}} visualizaç{{thread.views|pluralize:"ão,ões"}} |
					{{thread.answers}} resposta{{thread.answers|pluralize}}
				</h5>
				<p>
					<i class="fas fa-tags"></i>
					Tags
					{% for tag in thread.tags.all %}
						<a href="{% url 'forum:index_tagged' tag.slug%}">{{tag}}</a>{% if not forloop.last%},{% endif %}
					{% endfor %}
				</p>
				<a class="fright">Atualizado há {{thread.updated_at|timesince}}</a>
			</div>
			{% empty %}
			<h3>Não há discussões</h3>
			{% endfor %}

			<div class="pagination">
				{% if page_obj.has_previous %}
					<a href="?page={{page_obj.previous_page_number}}{%if request.GET.order%}&order={{request.GET.order}}{%endif%}">&laquo;</a>
				{% endif %}
				{% for page in paginator.page_range%}
				<span class="{% if page == page_obj.number%}active{%endif%}">
					<a href="?page={{page}}{%if request.GET.order%}&order={{request.GET.order}}{%endif%}">{{page}}</a>
				</span>
				{% endfor %}
				{% if page_obj.has_next %}
					<a href="?page={{page_obj.next_page_number}}{%if request.GET.order%}&order={{request.GET.order}}{%endif%}">&raquo;</a>
				{% endif %}
			</ul>
		</div>
</div>
{%endblock%}

Simplemooc/forum/templates/forum/thread.html
{%extends 'base.html'%}
{%block content%}
<div class="pure-g-r content-ribbon">
	<div class="pure-u-1">
		<ul class="breadcrumb">
			<li><a href="{% url 'core:home' %}">Início</a></li>
			<li>/</li>
			<li><a href="{% url 'forum:index' %}">Página de discussões</a></li>
			<li>/</li>
			<li><a href="{{object.get_absolute_url}}">{{object}}</a></li>
		</ul>
	</div>
	<div class="pure-u-1-3">
		<div class="pure-menu pure-menu-open">
			<ul>
				<li class="pure-menu-heading">Tópicos : </li>
				<li><a href="?order=updated_at"><i class="fas fa-sync"></i> Mais recentes</a></li>
				<li><a href="?order=views"><i class="fas fa-eye"></i> Mais visualizados</a></li>
				<li><a href="?order=answers"><i class="fas fa-comments"></i> Mais comentados</a></li>

				<li class="pure-menu-heading">Tags : </li>
				{% for tag in tags %}
				<li><a href="{% url 'forum:index_tagged' tag.slug%}"><i class="fas fa-tag"> {{tag}}</i></a></li>
				{% endfor %}
			</ul>
		</div>
	</div>
	<div class="pure-u-2-3">
		<div class="inner">
			<div class="well">
				<h2>{{object}}</h2>
				{{object.body|linebreaks}}
				<h5>Criado por {{object.user}}</h5>
				<p>
					<i class="fas fa-tags"></i>
					{%for tag in object.tags.all%}
					<a href="{%url 'forum:index_tagged' tag.slug%}">{{tag}}</a>{% if not forloop.last%}, {%endif%}
					{%endfor%}
					<a class="fright">Criado há {{object.created_at|timesince}}</a>
				</p>
			</div>
			<div class="well" id="div-comments">
				<h4>Respostas /
				<a class="fright" href="#responder">Responder</a></h4>
				{%for reply in object.thread_reply.all%}
				<hr>
				<p>
					<strong>{% if reply.author %}{{reply.author}}{%else%}(Usuário desconhecido){%endif%} disse há {{reply.created_at|timesince}}</strong>
					{{reply.reply|linebreaksbr}}
					{% if object.user == user %}
						<br>
						<a href="{% url 'forum:reply-incorrect' reply.pk %}" class="pure-button button-error reply-cancel-correct-lnk {% if not reply.correct%} hidden {% endif %}">Cancelar resposta correta</a>

						<a href="{% url 'forum:reply-correct' reply.pk %}" class="pure-button button-sucess reply-correct-lnk {% if reply.correct %} hidden {%endif%}%">Indicar resposta correta</a>

						<span class="fright label-sucess correct-reply-msg {% if not reply.correct%} hidden {%endif%}"> Resposta indicada pelo autor </span>	
					{% elif reply.correct %}
						<br>
						<span class="fright label-sucess"> Resposta indicada pelo autor </span>	
						
					{% endif %}
				</p>
				{%empty%}
				<strong>Não há respostas para esse tópico</strong>
				{%endfor%}
				<hr>
				<form class="pure-form pure-form-stacked" method="post" id = "responder">
					<fieldset>
						{%csrf_token%}
						{% for field in form%}
						<div class="pure-control-group">
							{{field.label_tag}}
							{{field}}
							{{field.errors}}
						</div>
						{% endfor %}
						<div class="pure-control">
							<button type="submit" class="pure-button pure-button-primary">Enviar</button>
						</div>
					</fieldset>
				</form>
			</div>
		</div>
	</div>
{%endblock%}
{% block scripts %}
<script type="text/javascript">
	$(".reply-cancel-correct-lnk").click(function(e){
		e.preventDefault()
		var $this = $(this)
		var $p = $this.closest("p")
		$.get($this.attr('href'), function(data){
			if (data.sucess){
				$p.find(".correct-reply-msg".addClass('hidden'));
				$this.addClass('hidden');
				$p.find(".reply-correct-link".removeClass('hidden'));
			}

			else{
				alert(data.message);
			}
		} , 'json');
		return false;
	});
	$(".reply-cancel-correct-lnk").click(function(e){
		e.preventDefault()
		var $this = $(this)
		var $p = $this.closest("p")
		$.get($this.attr('href'), function(data){
			if (data.sucess){
				$("#div-comments .correct-reply-msg").addClass('hidden');
				$("#div-comments .reply-cancel-correct-lnk").addClass('hidden');
				$("#div-comments .reply-correct-lnk").removeClass('hidden');

				$p.find(".correct-reply-msg".removeClass('hidden'))
				$this.addClass('hidden')
				$p.find(".reply-cancel-correct-lnk".removeClass('hidden'))
			}
			else{
				alert(data.message);
			}
		}, 'json');
		return false;
	});
</script>
{% endblock %}